version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    environment:
      POSTGRES_HOST: "postgres"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: yarn start

volumes:
  postgres: